### ISSUE TITLE
Is skydock still under-development?

### ISSUE THREAD

**Issue by missedone** [crosbymichael/skydock#97]
hi folks
i see no commit since Jul 28, 2014, though in the README, it mentioned:
> I plan on making some breaking changes soon to help skydns and skydock scale better. To stay up-to-date either watch this repo or follow me on twitter @crosbymichael.

see commit https://github.com/crosbymichael/skydock/commit/4c7549c08e480be549afc5d0343aac81247ea9c0

so i'm wondering whether this project is still under development or not?
i'm at the early stage on evaluating the auto service discovery for docker, the other alternative is [registrator](https://github.com/gliderlabs/registrator)

please mark it if development stopped, thanks anyway for sharing the project and most import the idea about auto service discovery.

**Comment by dogik** [comment]
+1 on this question

**Comment by dogik** [comment]
@missedone - thanks for the registrator link.

**Comment by crosbymichael** [comment]
There has been no changes recently on skydock.  Docker is currently integrating DNS discovery into 1.10 release so things like skydock will not be needed anymore.  

I'm hoping with the new networking changes that projects like this will not be needed anymore.

**Comment by dogik** [comment]
Thank you @crosbymichael
